name:          vdbms
version:       0.1.0.0
synopsis:      A variational database management system
homepage:      http://github.com/lambda-land/VDBMS
license:       BSD3
author:        OSU DB-PL
maintainer:    walkiner@oregonstate.edu
category:      Language

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/my-app#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5
- mtl
- sbv
- text
- megaparsec
- parsec
- HDBC
- QuickCheck
- mtl
- persistent >=2.9 && <3
- persistent-sqlite
- persistent-template
- conduit
- time

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings
  - FlexibleContexts
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - FlexibleInstances
  - DeriveDataTypeable
  - MultiParamTypeClasses
  - GADTs 
  - TypeFamilies 
  - QuasiQuotes 
  - TemplateHaskell
  - EmptyDataDecls


executables:
  vdbms:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - vdbms

tests:
  vsat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vdbms