name:          vdbms
version:       0.1.0.0
synopsis:      A variational database management system
homepage:      http://github.com/lambda-land/VDBMS
license:       BSD3
author:        Parisa Ataei
maintainer:    walkiner@oregonstate.edu
category:      Language

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/my-app#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && <1
- mtl 
# - mtl >=1.1 && <3
- sbv
- text
- megaparsec
- parsec
- HDBC
- QuickCheck
# - persistent >=2.9 && <3
# - persistent-sqlite
# - persistent-template
- conduit
- time 
# - time >= 1.0
- direct-sqlite
- HDBC-sqlite3 >= 2.3.3.1 
- HDBC-postgresql >= 2.3.2.6
- convertible
- bytestring
- directory
- clock
- haskelldb >= 2.2.5 
- pretty
- exceptions
- parser-combinators
# - lens
# - syb #scrap your boilerplate
#- template-haskell
# - pretty >= 1.0 && < 2
# - old-time >= 1.0 && < 2
# - old-locale >= 1.0 && < 2
# - directory >= 1.0 && < 2


library:
  source-dirs: src

default-extensions:
  - OverloadedStrings
  - FlexibleContexts
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - FlexibleInstances
  - DeriveDataTypeable
  - MultiParamTypeClasses
  - GADTs 
  - TypeFamilies 
  - QuasiQuotes 
  - TemplateHaskell
  - EmptyDataDecls
  - StandaloneDeriving
  - InstanceSigs
  - FunctionalDependencies


executables:
  vdbms:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - vdbms

tests:
  vdbms-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vdbms
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - QuickCheck