# Stack configuration file:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The resolver determines which packages are used to resolve the dependencies
# in the Cabal build file.
# https://www.stackage.org/lts-10.8
# resolver: lts-10.8
resolver: lts-11.14

system-ghc: false
allow-newer: true
packages: 
- .
# - lib/haskelldb
#- /Users/Paris/Desktop/VDBMS/lib/haskelldb
flags: {}
# extra-deps: [HDBC-sqlite3-2.3.3.1, time-1.9.2]
# extra-deps: [HDBC-sqlite3-2.3.3.1, haskelldb-2.2.5]
extra-deps: [HDBC-sqlite3-2.3.3.1]

extra-lib-dirs: 
 # - lib/haskelldb 
#  - /Users/Paris/Desktop/VDBMS/lib/haskelldb
   