# Stack configuration file:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The resolver determines which packages are used to resolve the dependencies
# in the Cabal build file.
# https://www.stackage.org/lts-10.8
resolver: lts-10.8

system-ghc: false
allow-newer: true
packages: 
- .
flags: {}
extra-deps: []
   