-- | vqs for employee database.
module VDBMS.UseCases.EmployeeUseCase.EmployeeQueries where

import VDBMS.QueryLang.RelAlg.Variational.Algebra
import VDBMS.UseCases.EmployeeUseCase.EmployeeSchema
import qualified VDBMS.Features.FeatureExpr.FeatureExpr as F
import qualified VDBMS.QueryLang.RelAlg.Variational.Condition as C
import VDBMS.VDB.Name
import VDBMS.DBMS.Value.CompOp
import Prelude hiding (Ordering(..))
import Database.HDBC 

-- import Data.Time.LocalTime
import Data.Time.Calendar

-- keep in mind that the employee use demos deploying
-- every single version for the client of spl. so qs
-- must be st the software generated by spl is actually
-- using it. i.e. qs aren't being run in the test, instead
-- they're running in deployment step. or better yet 
-- you can imagine that different divisions of the company
-- are using different versions of it. so qs demo situations
-- that the user/software has some information need that 
-- needs to get data from different versions. keep in mind
-- that the user/software can definitely specify the version
-- they're requiring at the end, which just requires applying
-- configuration to the final result of a vq or getting the
-- plain q of a vq and then running it on the appropriate 
-- variant. 

newtype QueryT = QueryT String
  deriving (Show, Eq)
-- 
-- Smart Constructors
--
-- | attaches the feature expression true to an attribute. 
trueAttr :: Attr -> OptAttribute
trueAttr a = (F.Lit True, genRenameAttr a)

genRenameAlgebra :: Algebra -> Rename Algebra
genRenameAlgebra alg = Rename Nothing alg

genRenameRelation :: Relation -> Rename Relation
genRenameRelation rel = Rename Nothing rel

tRef :: Relation -> Algebra 
tRef rel = TRef $ Rename Nothing rel 

joinTwoRelation :: Relation -> Relation -> Attr -> Algebra
joinTwoRelation rel1 rel2 commonAttr = Join (genRenameAlgebra (tRef rel1)) (genRenameAlgebra (tRef rel2)) join_cond
  where join_cond = C.Comp EQ (C.Att (qualifiedAttr rel1 commonAttr)) (C.Att (qualifiedAttr rel2 commonAttr))

-- | Join three relation(a,b,c) based on commonAttr. 
--   (rel1 join(rel1.commonAttr = rel2.commonAttr) rel2) join(rel1.commonAttr = rel3.commonAttr) rel3
joinThreeRelation :: Relation -> Relation -> Relation -> Attr -> Algebra
joinThreeRelation rel1 rel2 rel3 commonAttr = Join (genRenameAlgebra (joinTwoRelation rel1 rel2 commonAttr)) (genRenameAlgebra (tRef rel3)) cond 
  where cond = C.Comp EQ (C.Att (qualifiedAttr rel1 commonAttr)) (C.Att (qualifiedAttr rel3 commonAttr))

--
-- Constant values used for employee use cases
--

-- | the year 1991 condition
--   ModifiedJulianDay Int (Count days from 1858-11-17)
--   1991-01-01: ModifiedJulianDay 48257
--   1992-01-01: ModifiedJulianDay 48622

date19910101, date19920101 :: Day
date19910101 = ModifiedJulianDay 48257
date19920101 = ModifiedJulianDay 48622

-- | 1991-01-01 < hiredate < 1992-01-0
yearCond :: C.Condition 
yearCond = C.And (C.Comp GT (C.Val $ SqlLocalDate date19910101) (C.Att  hiredate))
                 (C.Comp LT (C.Att hiredate) (C.Val $ SqlLocalDate date19920101))

-- |  hiredate > 1991-01-01
yearAfterCond :: C.Condition 
yearAfterCond = C.Comp GT (C.Att hiredate) (C.Val $ SqlLocalDate date19910101) 

-- | employee id = 10004 condition
empCond :: C.Condition
empCond = C.Comp EQ (C.Att empno) (C.Val $ SqlInt32 10004)

empno_value :: SqlValue 
empno_value  = SqlInt32 10004

departno_value :: SqlValue
departno_value = SqlString "d001"

--
-- Queries based on Prima paper
--

-- 1(Q1A). 
-- first set of quesries:
-- taken from the prima paper, adjusted to the employee database. 
-- e.g. instead of year 2003, we have year 1991, etc. 
-- can be used for comparison in terms of expressiveness and brevity.
-- 

-- intent: return the salary value of the emp 10004
--         on the year 1991. 
-- query: 
-- prj_salary 
--    (sel_(empNo=10004, 1991-01-01<hiredate<1992-01-01)
--            prj_(empno, hiredate, salary) 
--                empacct join_(title=title) job)
--
-- the variatonal query of empQ1:
-- * v-query considering 5 versions
--   v3 <empQ1, empty>
-- 
-- note:
-- the year 1991 is included in variants v3, v4, and v5. we only
-- write the query for these variants for a fair comparison against
-- prima.

empQ1T :: QueryT
empQ1T = QueryT $ 
  "SELECT salary" ++
  "FROM (SELECT empno, hiredate, salary" ++
        "FROM empacct INNER JOIN job)" ++
  "WHERE empNo = 10004 AND 1991-01-01 < hiredate AND hiredate < 1992-01-01"

empQ1 :: Algebra
empQ1 = Proj [trueAttr salary] $ genRenameAlgebra $
          Sel (VsqlCond (C.And empCond yearCond)) $ 
            genRenameAlgebra $ joinTwoRelation empacct job title

empVQ1 :: Algebra
empVQ1 = AChc empv3 empQ1 Empty

-- 2(Q1B). 
-- intent: return the managers (of department d001) on
--         the year 1991.
-- variational query:
--   v3 <empQ2, empty>
-- plain query(empQ2):
-- prj_managerno (sel_(1991-01-01<hiredate<1992-01-01 and deptno = d001)
--                 empacct join_(managerno=empno) dept)
-- Note:
-- 1. Attribute deptno only exist in v3,v4,v5.
empQ2T :: QueryT
empQ2T = QueryT $
  "SELECT managerno" ++
  "FROM empacct INNER JOIN dept ON managerno = empNo" ++
  "WHERE deptno = d001 AND 1991-01-01 < hiredate AND hiredate < 1992-01-01"

empQ2 :: Algebra
empQ2 = Proj [trueAttr managerno] $ genRenameAlgebra $ 
                  Sel (VsqlCond cond) $ genRenameAlgebra $ 
                  joinTwoRelation empacct dept deptno
      where cond = (C.Comp EQ (C.Att deptno) (C.Val departno_value)) `C.And ` yearCond

-- | VQ2 or VQ2naive, which one should use??
empVQ2 :: Algebra
empVQ2 = AChc empv3 empQ2 Empty

-- 3 (Q2A). 
-- intent: find all managers that the employee 10004 worked with,
--         on the year 1991. 
-- variational query:
--   v3 <empQ3, empty>
--
-- plain query(empQ3):
-- prj_managerno (dept join_(deptno=deptno) 
--                prj_deptno (sel_(empNo=10004, 1991-01-01<hiredate<1992-01-01) empacct))
-- note:
-- the naive and manually optimized queries are basically the same.
empQ3T :: QueryT
empQ3T = QueryT $
  "SELECT managerno" ++
  "FROM empacct join dept on deptno" ++  
  "WHERE empno = 10004 AND 1991-01-01 < hiredate AND hiredate < 1992-01-01) as t1"

empQ3 :: Algebra
empQ3 = Proj [trueAttr managerno] $ genRenameAlgebra $ 
  Sel (VsqlCond ((yearCond `C.And` (C.Comp EQ (C.Att empno) (C.Val empno_value)) ))) $ genRenameAlgebra $ 
  joinTwoRelation empacct dept deptno 

-- | v3 or v4 or v5 <q3, empty>
empVQ3 :: Algebra
empVQ3 = AChc empv3 empQ3 Empty

-- 4(Q2B).
-- intent: find all salary values of managers in all history,
--         during the period of manager appointment. (the periods
--         of salary and manager appointment need to overlap).
--         answer using data valid on the year 1991.
-- * variational query:
--   v3 <empQ4, empty>
-- 
-- * palin query(empQ4):
--    prj_(managerno, salary) 
--     sel_(1991-01-01<hiredate<1992-01-01) 
--       (empacct join_(title = title) job join_(managerno = empno) dept)
--      
-- note: 
-- check to see if the join only occurs for valid variants!!
-- i.e. ... join dept is only valid for v3, v4, and v5. 
-- and ... join job is not valid for v5.
-- and there's no way to get the period of manager appointment.

empQ4:: Algebra
empQ4 = Proj [trueAttr managerno, trueAttr salary] $ genRenameAlgebra $ 
          Sel (VsqlCond yearCond) $ genRenameAlgebra $ 
          Join (genRenameAlgebra join_empacct_job) (genRenameAlgebra (tRef dept)) cond 
    where join_empacct_job = joinTwoRelation empacct job title 
          cond = C.Comp EQ (C.Att empno) (C.Att managerno)

empVQ4 :: Algebra
empVQ4 = AChc empv4 empQ4 Empty

-- 5(Q3A).
-- Intent: Find the historical managers of department where the employee 10004 worked, in all history. 
--         (The period of their appointments don't need to overlap.)
--         Answer using data valid on the year 1991.
-- Process: 1. find the departments where 10004 worked
--          2. get managerno from those departments 
-- 
-- * variational queries:
--   v3 <empQ5, empty> 
-- * plain queries(empQ5):
--       SELECT managerno
--       from dept
--       where deptno in 
--       (SELECT deptno 
--       FROM empacct
--       where empno = 10004 and 1991-01-01<hiredate<1992-01-01 )

empQ5 :: Algebra
empQ5 = Proj [trueAttr managerno] $ genRenameAlgebra $ 
          Sel (VsqlIn deptno sub) $ genRenameAlgebra $ 
            tRef dept  
      where sub = Proj [trueAttr deptno] $ genRenameAlgebra $ 
                    Sel (VsqlCond cond) $ genRenameAlgebra $ 
                    tRef empacct
            cond = (C.Comp EQ (C.Att empno) (C.Val empno_value)) `C.And ` yearCond

empVQ5 :: Algebra
empVQ5 = AChc empv3 empQ5 Empty

--6(Q3B).
-- intent: find all salary values of managers in all history.
--         (the periods of salary and manager appointment 
--         don't need to overlap.) 
--         answer using data valid on the year 1991.
-- query:
-- 
-- note: there's no way to get the period of manager appointment.
empVQ6 :: Algebra
empVQ6 = empVQ4

-- 7(Q4A).
-- intent: For all managers that the employee 10004 with, find all the departments that the manager managed. 
--         (10004's and the manager's affiliation with a single department should overlap, but
--         the manager's manager position periods do not need to overlap, naturally.)
--         Answer using data valid on the year 1991.
-- Process: 1. get managers that 10005 with
--          2. get departments for those managers 
-- 
-- * variational queries:
--   v3  <empQ7, empty>
-- * plain queries for each version:
--      SELECT deptname 
--      from dept 
--      where managerno in 
--      (SELECT managerno 
--      FROM v3_empacct JOIN dept ON v3_empacct.deptno = dept.deptno
--      where empno = 10004 and 1991-01-01<hiredate<1992-01-01 ) 
--     ** subquery here is the same with empQ3
empQ7 :: Algebra
empQ7 = Proj [trueAttr deptname] $ genRenameAlgebra $ 
          Sel (VsqlIn managerno empQ3) $ genRenameAlgebra $ 
            tRef dept

-- | v3 or v4 or v5 <q2, empty>
empVQ7 :: Algebra
empVQ7 = AChc empv3 empQ7 Empty

-- 8(Q4B).
-- intent: For all managers, find all managers in the department that he/she worked in. (two worked during the same period)
--         (non-temporal join follwed by temporal-join)
--          Answer using data valid on the year 1991.
-- 
-- Process: 1. Find departments and hiredate of manager worked in
--          2. Find managers where has same departments and hiredate except itself
-- 
-- * variational queries:
-- * plain queries for each version:
-- Note: Two worked during same period, we consider it as two people hire at the same hiredate.
empQ8 :: Algebra
empQ8 = undefined

empVQ8 :: Algebra
empVQ8 = undefined

-- 
-- Q9-Q16 is a relaxation of Q1-Q8, in terms of period.
-- 

-- 9(Q5A).
-- intent: return the salary values of the emp 10004 on 
--         1991-01-01 or after. 
-- 
-- plain query:
-- prj_salary 
--    (sel_(empNo=10004, hiredate>1991-01-01)
--            prj_(empno, hiredate, salary) 
--                empacct join_(title=title) job)
-- 
-- the variatonal query of empQ1:
-- * v-query considering 5 versions
--   v1 < q1_v1, (v2 or v3 or v4) < q1_v2v3v4, v5 < q1_v4, empty>>>
-- * plain queries for each versiton 
--   q1_v1:  prj_salary 
--          (sel_(empNo=10004,hiredate>1991-01-01))
--          (job join_(title=title) engineerpersonnel) join_(tiltle=tiltle) otherpersonnel)
--   q1_v2v3v4:
--     prj_salary 
--     (sel_(empNo=10004, hiredate>1991-01-01>))
--     (empacct join_(title=title) job)
--   q1_v5:
--      prj_salary
--     (sel_(empNo=10004, hiredate>1991-01-01))
--     empacct 
empQ9T :: QueryT
empQ9T = QueryT $ 
  "SELECT salary" ++
  "FROM (SELECT empno, hiredate, salary" ++
        "FROM empacct INNER JOIN job)" ++
  "WHERE empNo = 10004 AND hiredate > 1991-01-01"

empVQ9 :: Algebra
empVQ9 = AChc empv1 empQ9_v1 $ AChc (F.Or empv2 (F.Or empv3 empv4)) empQ9_v2v3v4 $ AChc empv5 empQ9_v5 Empty
            where empQ9_v1 = Proj [trueAttr salary] $ genRenameAlgebra $ 
                              joinThreeRelation job engineerpersonnel otherpersonnel title 
                  empQ9_v2v3v4 = Proj [trueAttr salary] $ genRenameAlgebra $
                                  Sel (VsqlCond (C.And empCond yearAfterCond)) $ 
                                   genRenameAlgebra $ joinTwoRelation empacct job title
                  empQ9_v5 = Proj [trueAttr salary] $ genRenameAlgebra $ 
                              Sel (VsqlCond (C.And empCond yearAfterCond)) $ genRenameAlgebra $ 
                                tRef empacct 

-- 10(Q5B). 
-- intent: return the managers (of department d001) on
--         1991-01-01 or after.
-- query:
-- prj_managerno (sel_(hiredate>1991-01-01and deptno = d001)
--                 empacct join_(managerno=empno) dept)
-- Note:
-- 1. Attribute deptno only exist in v3,v4,v5.
-- v3 or v4 or v5 <q2, empty> OR v3 <q2, v4 < q2, v5 <q2, Empty>>>???
empQ10T :: QueryT
empQ10T = QueryT $
  "SELECT managerno" ++
  "FROM empacct INNER JOIN dept ON managerno = empNo" ++
  "WHERE deptno = d001 AND hiredate > 1991-01-01 "

empQ10 :: Algebra
empQ10 = Proj [trueAttr managerno] $ genRenameAlgebra $ 
                  Sel (VsqlCond cond) $ genRenameAlgebra $ 
                  joinTwoRelation empacct dept deptno
      where cond = (C.Comp EQ (C.Att deptno) (C.Val departno_value)) `C.And ` yearAfterCond

-- | VQ2 or VQ2naive, which one should use??
empVQ10 :: Algebra
empVQ10 = AChc (empv3 `F.Or` empv4 `F.Or` empv5) empQ10 Empty

empVQ10naive :: Algebra
empVQ10naive = AChc empv3 empQ10 (AChc empv4 empQ10 $ AChc empv5 empQ10 Empty)

-- 11(Q6A)
-- intent: find all managers that employee 10004 worked with,
--         with overlapping period. answer using data valid 
--         on or after 1991-01-01.
-- query:
-- prj_managerno (dept join_(deptno=deptno) 
--                prj_deptno (sel_(empNo=10004, hiredate>1991-01-01) empacct))
-- note:
-- the naive and manually optimized queries are basically the same.
empQ11T :: QueryT
empQ11T = QueryT $
  "SELECT managerno" ++
  "FROM empacct join dept on deptno" ++  
  "WHERE empno = 10004 AND hiredate > 1991-01-01  as t1"

empQ11 :: Algebra
empQ11 = Proj [trueAttr managerno] $ genRenameAlgebra $ 
  Sel (VsqlCond ((yearAfterCond `C.And` (C.Comp EQ (C.Att empno) (C.Val empno_value)) ))) $ genRenameAlgebra $ 
  joinTwoRelation empacct dept deptno 

-- | v3 or v4 or v5 <q2, empty>
empVQ11 :: Algebra
empVQ11 = AChc (empv3 `F.Or` empv4 `F.Or` empv5) empQ10 Empty

empVQ11naive :: Algebra
empVQ11naive = AChc empv3 empQ11 (AChc empv4 empQ11 $ AChc empv5 empQ11 Empty)

-- 12(Q6B)
-- intent: find all salary values of managers in all history.
--         (the periods of salary and manager appointment need
--         to overlap) answer using data valid on or after
--         1991-01-01.
-- * variational query:
--   v3 o v4<empQ12_v3v4, v5<empQ12_v5, empty>>
-- 
-- * palin query for each version:
--   * for v3, v4:
--    prj_(managerno, salary) 
--     sel_(hiredate>1991-01-01) 
--       (empacct join_(title = title) job join_(managerno = empno) dept) 
--   * for v5:
--    prj_(managerno, salary) 
--     sel_(hiredate>1991-01-01) 
--       (empacct join_(managerno = empno) dept)      
-- note: 
-- check to see if the join only occurs for valid variants!!
-- i.e. ... join dept is only valid for v3, v4, and v5. 
-- and ... join job is not valid for v5.
-- and there's no way to get the period of manager appointment.
empQ12_v3v4 :: Algebra
empQ12_v3v4 = Proj [trueAttr managerno, trueAttr salary] $ genRenameAlgebra $ 
          Sel (VsqlCond yearAfterCond) $ genRenameAlgebra $ 
          Join (genRenameAlgebra join_empacct_job) (genRenameAlgebra (tRef dept)) cond 
    where join_empacct_job = joinTwoRelation empacct job title 
          cond = C.Comp EQ (C.Att empno) (C.Att managerno)

empQ12_v5 :: Algebra
empQ12_v5 = Proj [trueAttr managerno, trueAttr salary] $ genRenameAlgebra $ 
          Sel (VsqlCond yearAfterCond) $ genRenameAlgebra $ 
          Join (genRenameAlgebra (tRef empacct)) (genRenameAlgebra (tRef dept)) cond 
    where cond = C.Comp EQ (C.Att empno) (C.Att managerno)

empVQ12 :: Algebra
empVQ12 = AChc (F.Or empv3 empv4)
            empQ12_v3v4
            (AChc empv5 empQ12_v5 Empty)

-- 13(Q7A)
-- intent: find the historical managers of department where
--         the employee 10004 worked, in all history.
--         (the period of their appointments don't need to 
--         overlap.) answer using data valid on or after
--         1991-01-01.
-- Process: 1. find the departments where 10004 worked
--          2. get managerno from those departments 
-- 
-- * variational queries:
--   (v3 or v4 or v5) <empQ13, empty> or v3<empQ13, v4<empQ13, v5 <empQ13, empty>> ??? 
-- * plain queries for each version:
--   * For v3,v4,v5:
--       SELECT managerno
--       from dept
--       where deptno in 
--       (SELECT deptno 
--       FROM empacct
--       where empno = 10004 and hiredate>1991-01-01 )
-- 
empQ13 :: Algebra
empQ13 = Proj [trueAttr managerno] $ genRenameAlgebra $ 
          Sel (VsqlIn deptno sub) $ genRenameAlgebra $ 
            tRef dept  
      where sub = Proj [trueAttr deptno] $ genRenameAlgebra $ 
                    Sel (VsqlCond cond) $ genRenameAlgebra $ 
                    tRef empacct
            cond = (C.Comp EQ (C.Att empno) (C.Val empno_value)) `C.And ` yearAfterCond

empVQ13 :: Algebra
empVQ13 = AChc (empv3 `F.Or` empv4 `F.Or` empv5) empQ13 Empty

-- 14(Q7B)
-- intent: find all salary values of managers in all history.
--         (the periods of salary and manager appointment don't
--         need to overlap)
--         answer using data valid on or after the year 1991. 
empVQ14 :: Algebra
empVQ14 = empVQ12

-- 15(Q8A)
-- intent: for all managers that the employee 10004 worked with, 
--         find all the departments that the manager managed.
--         (temporal join followed by non-temporal join)
--         (10004's and the manager's affiliation with a single
--         department should overlap, but the manager's manager 
--         position periods do not need to overlap, naturally.)
--         anwer using data valid on or after the year 1991.
-- Process: 1. get managers that 10005 with
--          2. get departments for those managers 
-- 
-- * variational queries:
--   (v3 or v4 or v5) <empQ15, empty> or v3<empQ15, v4<empQ15, v5 <empQ15, empty>> ??? 
-- * plain queries for each version:
--   * For v3,v4,v5:
--      SELECT deptname 
--      from dept 
--      where managerno in 
--      (SELECT managerno 
--      FROM v3_empacct JOIN dept ON v3_empacct.deptno = dept.deptno
--      where empno = 10004 and hiredate>1991-01-01 ) 
--     ** subquery here is the same with empQ11
empQ15 :: Algebra
empQ15 = Proj [trueAttr deptname] $ genRenameAlgebra $ 
          Sel (VsqlIn managerno empQ11) $ genRenameAlgebra $ 
            tRef dept

-- | v3 or v4 or v5 <q2, empty>
empVQ15 :: Algebra
empVQ15 = AChc (empv3 `F.Or` empv4 `F.Or` empv5) empQ15 Empty


empVQ15naive :: Algebra
empVQ15naive = AChc empv3 empQ15 $ AChc empv4 empQ15 $ AChc empv5 empQ15 Empty

-- 16(Q8B)
-- intent: for all managers, find all managers in the department 
--         that he/she worked in. (two worked during the same 
--         period) (non-temporal join followed by temporal-join)
--         answer using data valid on or after the year 1991.
empVQ16 :: Algebra
empVQ16 = undefined

